/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed one million.

*/

#include <stdio.h>

int a,b;

int fibonacci() {
int c;

if (a<b) {
c=b;b+=a;
a=c;c=b;
} else {
c=a;a+=b;
b=a;c=b;
}

return c;

}

int main() {
int x,temp;
a=1;b=2;
x=2;

while (x<=1000000) {
temp=fibonacci();
if (temp%2 == 0) x+=temp;
}

printf("x=%d\n", x);

return 0;

}
